### ISSUE TITLE
Investigate possible frame pause issue

### ISSUE THREAD

**Issue by sr229** [sr229/animegrep#6]
It seems that when @daniel-Jones made the Mya-nee video, there is severe frame pausing which last for a few seconds. I don't think that's intended so we'll need to investigate that if that's within OP's NLE or something within `mkvmerge` / ``ffmpeg``.

**Comment by daniel-Jones** [comment]
do note I merged them separately from the script, I'm not sure what method I used. I shall re-create the video with the current script and see how that goes.

**Comment by daniel-Jones** [comment]
https://gnupluslinux.com/myanee.webm a version merged with the script before c398ded.

This should be much longer. It is only merging ~99 files and the subs are removed. I wont open an issue until #9 is resolved at it might fix it.

**Comment by daniel-Jones** [comment]
https://gnupluslinux.com/out.mkv is merged from before c398ded. It seems to me like there are no pauses, though I only skipped through...

**Comment by sr229** [comment]
Looks like I don't see this issue appearing anywhere again so I'll assume its already fixed. Closing!
